services:
  web:
    build: .
    container_name: mynav-web
    ports:
      - "8080:80"
    volumes:
      - ./config:/var/www/html/config
      - ./database/backups:/var/www/html/database/backups
      - ./admin/assets/uploads:/var/www/html/admin/assets/uploads
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
